[tool.poetry]
name = "advent-2024"
version = "0.1.0"
description = "Advent of Code 2024 Solutions"
authors = ["Your Name"]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.0"
pytest = "^7.4.0"